title:              Jd's Tech Blog
email:              ranadaking45@gmail.com
description:        Tech blog for aspiring geeks
author:             Jaideep Rana
baseurl:            ""
url:                "https://jaideeprana.github.io"

# Social Profiles
twitter_username:   ranadaking451
github_username:    jaideeprana
facebook_username:  Sant.Rampal.Ji.Ka.Dass
instagram_username:
linkedin_username:

google_analytics:   G-XL95SPQF7Q

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
